### ISSUE TITLE
Dependency on tokio_test is missing in the crate

### ISSUE THREAD

**Issue by graywolf** [tokio-rs/async-stream#102]
Hello,

when I check the Cargo.toml file at v0.3.5 ( https://github.com/tokio-rs/async-stream/blob/v0.3.5/async-stream/Cargo.toml ), I see tokio_test in there:

```
tokio-test = "0.4"
```

However, crates.io does not list it: https://crates.io/crates/async-stream/0.3.5/dependencies

When I check the actual crate ( https://crates.io/api/v1/crates/async-stream/0.3.5/download ), the tokio_test is indeed not in the Cargo.toml.orig:

```
[dev-dependencies]
futures-util = "0.3"
rustversion = "1"
tokio = { version = "1", features = ["full"] }
trybuild = "1"
```

Sorry if this is a stupid question, I do not know rust much, but how was the crate generated?  I would have assume it would match the source code at the git tag.

Thank you

**Comment by taiki-e** [comment]
I don't remember exactly what happened, but I suspect I could not publish without removing it due to circular dependencies.

https://github.com/tokio-rs/tokio/blob/b32826bc937a34e4d871c89bb2c3711ed3e20cdc/tokio-test/Cargo.toml#L22

**Comment by taiki-e** [comment]
This is for workaround a Cargo bug and is not a problem that can be addressed on our end at this time. See the linked issues.
