### ISSUE TITLE
Module doesn't build on ARM target

### ISSUE THREAD

**Issue by mstepien-mobica** [tokio-rs/async-stream#108]
error: cannot produce proc-macro for `async-stream-impl v0.3.5` as the target `aarch64-unknown-linux-gnu` does not support these crate types

**Comment by taiki-e** [comment]
I guess this is https://github.com/rust-lang/rust/issues/78210.

**Comment by taiki-e** [comment]
This seems to be a problem with the way you tried to compile the code, or with the proc-macro itself, and does not seem to be a problem with this project itself, so I'm going to close this.
