### ISSUE TITLE
failure::format_err! inside try_stream! strange behavior

### ISSUE THREAD

**Issue by serejkaaa512** [tokio-rs/async-stream#22]
If using format_err! macro inside try_stream!:
```
use failure::*;

pub fn stream() -> impl Stream<Item = failure::Fallible<i32>> + Send {
    async_stream::try_stream! {
        Err(format_err!("adasdasd"))?;
        for i in (1..10) {
            yield 123;
        }
    }
}
```
It doesn't compile - `*mut (dyn std::ops::Fn() + 'static)` cannot be shared between threads safely.
But when using it without format_err!: 
```
use failure::*;

#[derive(Debug, Fail)]
#[fail(display = "my error")]
pub struct MyError;

pub fn stream() -> impl Stream<Item = Fallible<i32>> + Send {
    async_stream::try_stream! {
        Err(MyError)?;
        for i in (1..10) {
            yield 123;
        }
    }
}
```
Compiler says all Ok.

**Comment by taiki-e** [comment]
`failure::format_err!` calls `format!` internally. And `std::fmt::Arguments`(called by `format!`) are not implemented `Send`, so any future containing them will not be implemented `Send`.

related: https://github.com/rust-lang/rust/issues/64960, https://github.com/rust-lang/rust/pull/64856

**Comment by carllerche** [comment]
I will close the issue as this is an upstream thing.
