### ISSUE TITLE
Example for Streaming Borrowed Item

### ISSUE THREAD

**Issue by elbaro** [tokio-rs/async-stream#34]
For performance reasons, I'd like to have one reusable bufffer `buf: Vec<u8>` and yield a `&buf[..]`. The user needs to drop the reference before another `next().await`.

Unlike [streaming-iterator](https://github.com/sfackler/streaming-iterator) which only requires `&mut self` during `next()`, this is not easy in async-stream because the generator loop keeps holding the mutable reference.

```
pub struct Reader<R: AsyncRead> {
    r: R,
    buf: Vec<u8>,
}

impl<R: AsyncRead + Unpin> Reader<R> {
    pub fn stream(self: &mut Self) -> impl futures::Stream<Item = Result<&[u8]>> {
        async_stream::try_stream! {
          loop {
            ..
            yield &self.buf[..];
         }
  }
}
```

```
error[E0502]: cannot borrow `self.buf` as mutable because it is also borrowed as immutable
  --> src/main.rs:20:9
   |
20 | /         async_stream::try_stream! {
21 | |
22 | |             loop {
...  |
42 | |                 yield &self.buf[..];
   | |                        -------- immutable borrow occurs here
43 | |             }
44 | |         }
   | |         ^
   | |         |
   | |         mutable borrow occurs here
   | |_________lifetime `'1` appears in the type of `__yield_tx`
   |           argument requires that `self.buf` is borrowed for `'1`
   |
```

It would be great to see an example of yielding borrowed data.

**Comment by Darksonn** [comment]
This isn't possible while still implementing the `Stream` trait. You would need to introduce a new `StreamingStream` trait for that.

**Comment by koivunej** [comment]
Having considered similar situtation, I think the best action right now might be to use [bytes](https://docs.rs/bytes/0.5.6/bytes/) to achieve what you are hoping to get with streaming stream at this time. Basically replace your `Vec<u8>` with [`BytesMut`](https://docs.rs/bytes/0.5.6/bytes/struct.BytesMut.html), then `yield buffer.split().freeze()`.

**Comment by elbaro** [comment]
I managed to solve this using `Rc`.

```
-> impl futures::Stream<Item = Result<Rc<Data>>>
...

let mut data_rc = Rc::new(Data::default());
loop {
  // update data
  {
    let data = Rc::get_mut(&mut data_rc).expect("You should drop Rc<Data> after use");
    // incremental update to changed fields
    data.field1 = ..;
    data.field2 = ..;
  }
  {
    yield data.clone();
    // the user should drop Rc<Data> at this point
  }
}
```
This is runtime-check not compile-time check.

@koivunej Thanks, I heard it for the first time. Can you reuse `BytesMut.split().freeze()` after yield? or allocate more?

**Comment by koivunej** [comment]
> Can you reuse BytesMut.split().freeze() after yield? or allocate more?

@elbaro assuming the yielded `Bytes` is dropped **before** your stream next attempts to write to it's `BytesMut` counterpart, it should [reuse](https://github.com/tokio-rs/bytes/blob/6fdb7391ce83dc71ccaeda6a54211ce723e5d9a5/src/bytes_mut.rs#L614-L630) (disclaimer: I might be misunderstanding). While it may be impossible to control when the yielded value gets dropped, in [ipfs-http](https://github.com/rs-ipfs/rust-ipfs/tree/master/http) where I use `async_stream` extensively the [HTTP response streams](https://docs.rs/hyper/0.13.7/hyper/body/struct.Body.html#method.wrap_stream) at least _seem_ to consume the yielded `Bytes` before polling for next item. For more complicated cases which would extend the lifetime of the yielded `Bytes` for buffering and whatnot, one could either pool the bytes instances or just let the allocator do that for you and let bytes allocate.

**Comment by elbaro** [comment]
Then Bytes may allow concurrent processing (which means the consumer can hold multiple freezed data) by having a large ring buffer and freeze non-overlapping segments independently. This can provide an interface like rayon's par_iter. Thanks for the comment.
