### ISSUE TITLE
Proc macros in expression position are stable in 1.45+

### ISSUE THREAD

**Issue by abonander** [tokio-rs/async-stream#35]
Proc macros in expression position have been stable for a couple releases now, it shouldn't be necessary to use hacks anymore.

**Comment by taiki-e** [comment]
Closing as this has already been addressed in v0.3 (https://github.com/tokio-rs/async-stream/pull/30)

**Comment by taiki-e** [comment]
Oh, docs still mention it. It seems I forgot to remove them.
